CREATE TABLE groovy_script (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	script_name varchar(255) not null,
	script_text varchar(255) not null
);

create sequence person_sequence start with 1 increment by 1;